name: agent
description: AI Tutor Agent
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.3.0
  file_picker: ^9.1.0
  google_fonts: ^5.1.0
  flutter_markdown: ^0.6.18
  js: ^0.6.7
  intl: ^0.17.0
  markdown_widget: ^2.3.2+6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true